/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.stackable.druid.opaauthorizer;

import org.apache.druid.server.security.Authorizer;

public class Library {
    public boolean someLibraryMethod() {
        Authorizer

        return true;
    }
}
