/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.stackable.druid.opaauthorizer;

import org.apache.druid.server.security.*;

public class OpaAuthorizer implements Authorizer {

    @Override
    public Access authorize(AuthenticationResult authenticationResult, Resource resource, Action action) {
        return Access.OK;
    }
}
