# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
---
name: Java CI with Gradle

on:
  push:
    branches:
      - main
      - staging
      - trying
      - "renovate/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Set up JDK 11
        uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3 # tag=v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Set up OpenPolicyAgent
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/v0.33.1/opa_linux_amd64_static
          chmod +x opa
          sudo mv opa /usr/local/bin/opa
      - name: Build with Gradle
        run: ./gradlew build
